### ISSUE TITLE
[Question] Where I would put an specific query?

### ISSUE THREAD

**Issue by cardoso010** [vinicius73/graphql-start-project#3]
Hello, 
I would like to know where I can put an specific query in this architecture like an query with any join? Because I saw that you are doing generic query.

Thanks in advance!

**Comment by vinicius73** [comment]
Hi!
Where it is most convenient for you.

```gql
type RootQuery {
  # ...
  bestSellers(pagination: PaginationInput): ProductsResource!
}
```

or

```gql
type Client {
  # ...
  bestSellers(pagination: PaginationInput): ProductsResource!
}
```

Than, you implement the resolver.

`RootQuery.resolvers.js`
```js
module.exports = {
  bestSellers (root, args, { services }) => {
    return services.db...
  }
}
```

or

`Client.resolvers.js`
```js
module.exports = {
  bestSellers (root, args, { services }) => {
    //
  }
}
```

**Comment by cardoso010** [comment]
Thank you for answer @vinicius73.
